### ISSUE TITLE
Error on `? Copy .env.example to .env? No`

### ISSUE THREAD

**Issue by karltaylor** [imperodesign/generator-impero#10]
I tried 

`? Copy .env.example to .env? Yes`
`? Copy .env.example to .env? No`

and they both returned:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at writing (/Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/generators/app/index.js:148:13)
    at Object.<anonymous> (/Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/node_modules/yeoman-generator/lib/base.js:431:23)
    at /Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/node_modules/run-async/index.js:26:25
    at /Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/node_modules/run-async/index.js:25:19
    at /Users/karl/.nvm/versions/node/v6.4.0/lib/node_modules/generator-impero/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by SamHH** [comment]
https://github.com/imperodesign/generator-impero/commit/314ec8fd4a4d35be825e6588fec1300e5c4161f7

Fixed in v1.0.0-alpha5. Run `npm i -g generator-impero` again to update 👍
